pipeline:
  name: spring-ci
  identifier: springci
  projectIdentifier: Harness_Test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      cd SmallestSpringApp  
                      mvn -B clean package  
                      mvn -B test
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        build: <+input>
